server:
  port: 8080

do: 
  space: 
    key: DO00K94UMWWG9ZNFEN6H
    secret: VUrjqUkM+FwEKYMckLKXkm8WfbIRYR1f87VamHImdVM
    endpoint: https://nyc3.digitaloceanspaces.com
    region: nyc3
    bucket: image-storage

spring: 
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 200MB